# Generated by Django 5.2 on 2025-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_reportedposts_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
