# Generated by Django 5.2 on 2025-11-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_pinned"),
        ("posts", "0006_reaction"),
    ]

    operations = []
