# Generated by Django 5.2 on 2025-11-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
