# Generated by Django 5.2 on 2025-11-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
