# Generated by Django 5.2 on 2025-11-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_historicalcomment_historicalpost_and_more"),
        ("posts", "0007_merge_0006_post_pinned_0006_reaction"),
    ]

    operations = []
