# Generated by Django 5.2 on 2025-11-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_remove_post_tags"),
        ("users", "0009_user_receive_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="users.tag"
            ),
        ),
    ]
