# Generated by Django 5.2 on 2025-11-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_merge_20251125_0100"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
