# Generated by Django 5.2 on 2026-01-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_historicalpost_pinned"),
        ("users", "0014_merge_20251214_1927"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="users.tag"
            ),
        ),
    ]
