# Generated by Django 5.2 on 2025-11-25 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_merge_0006_post_pinned_0006_reaction"),
        ("posts", "0009_post_tags"),
    ]

    operations = []
