# Generated by Django 5.2 on 2026-01-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
