# Generated by Django 5.2 on 2026-02-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('love', 'Love'), ('appreciate', 'Appreciate'), ('respect', 'Respect'), ('support', 'Support'), ('inspired', 'Inspired'), ('helpful', 'Helpful'), ('celebrate', 'Celebrate'), ('laugh', 'Laugh'), ('fire', 'Fire'), ('clap', 'Clap'), ('grateful', 'Grateful'), ('mindblown', 'Mind Blown')], max_length=20),
        ),
    ]
