# Generated by Django 5.2 on 2025-12-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_historicalpost_pinned"),
        ("posts", "0010_merge_20251124_1801"),
    ]

    operations = []
