# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_alter_reaction_reaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
