# Generated by Django 5.2 on 2026-01-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_historicalpost_anonymous_post_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
