# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_comment_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
