# Generated by Django 5.2 on 2026-04-14 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_post_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpost",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(1000)]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(1000)]
            ),
        ),
    ]
