# Generated by Django 5.2 on 2025-04-28 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "participants",
                    models.ManyToManyField(related_name="chats", to="users.user"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image_content",
                    models.ImageField(blank=True, null=True, upload_to="post_images"),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="chats.chat"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="users.user"
                    ),
                ),
            ],
        ),
    ]
