# Generated by Django 5.1.6 on 2025-05-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="chat_id",
            new_name="chat",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="user_id",
            new_name="user",
        ),
    ]
