# Generated by Django 5.0.6 on 2025-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_groupmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="group_images"),
        ),
    ]
