# Generated by Django 5.0.6 on 2025-06-19 10:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_groupmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
