# Generated by Django 5.0.6 on 2025-06-19 22:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_alter_groupmessage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image_content",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
