# Generated by Django 5.2 on 2026-02-18 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0008_historicalchat_historicalgroupmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="hidden_by",
            field=models.ManyToManyField(
                blank=True, related_name="hidden_chats", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
