# Generated by Django 5.2 on 2026-05-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0010_chatreadstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalchat",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
    ]
