# Generated by Django 5.2 on 2026-05-30 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0010_chatreadstatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("love", "Love"),
                            ("appreciate", "Appreciate"),
                            ("respect", "Respect"),
                            ("support", "Support"),
                            ("inspired", "Inspired"),
                            ("helpful", "Helpful"),
                            ("celebrate", "Celebrate"),
                            ("laugh", "Laugh"),
                            ("fire", "Fire"),
                            ("clap", "Clap"),
                            ("grateful", "Grateful"),
                            ("mindblown", "Mind Blown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chats.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("message", "user", "reaction_type")},
            },
        ),
    ]
