# Generated by Django 5.2 on 2026-06-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0011_chat_is_group_historicalchat_is_group_alter_chat_id_and_more"),
        ("chats", "0011_messagereaction"),
    ]

    operations = []
