# Generated by Django 5.2 on 2026-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0012_merge_20260615_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmessage",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Sent"), (2, "Delivered"), (3, "Read")], default=1
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Sent"), (2, "Delivered"), (3, "Read")], default=1
            ),
        ),
    ]
