# Generated by Django 5.2 on 2025-04-28 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=127, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=127)),
                ("full_name", models.CharField(max_length=127)),
                ("pronouns", models.CharField(blank=True, max_length=63, null=True)),
                ("title", models.CharField(blank=True, max_length=63, null=True)),
                (
                    "primary_organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("other_organizations", models.TextField(blank=True, null=True)),
                ("other_networks", models.TextField(blank=True, null=True)),
                ("about_me", models.TextField(blank=True, null=True)),
                ("skills_interests", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_image"),
                ),
                (
                    "profile_header",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_header"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
