# Generated by Django 5.2 on 2025-11-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_receive_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
