# Generated by Django 5.2 on 2025-11-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_facebook_url_user_instagram_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="twitter_url",
            new_name="x_url",
        ),
    ]
