# Generated by Django 5.2 on 2025-12-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_historicaltag_historicaluser"),
        ("users", "0010_report"),
    ]

    operations = []
