# Generated by Django 5.2 on 2025-12-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_historicaltag_historicaluser"),
        ("users", "0011_rename_twitter_url_user_x_url"),
    ]

    operations = []
