# Generated by Django 5.2 on 2025-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_merge_20251212_1842"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="x_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
