# Generated by Django 5.2 on 2025-12-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_merge_0010_historicaltag_historicaluser_0010_report"),
        ("users", "0013_historicaluser_facebook_url_and_more"),
    ]

    operations = []
