# Generated by Django 5.2 on 2026-02-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_merge_20251214_1927"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
