# Generated by Django 5.2 on 2026-02-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_merge_20251214_1927"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
