# Generated by Django 5.2 on 2026-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="allow_dms",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="show_in_directory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_dms",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_in_directory",
            field=models.BooleanField(default=True),
        ),
    ]
