# Generated by Django 5.2 on 2026-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_historicaluser_is_verified_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="bluesky_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bluesky_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
