# Generated by Django 5.2 on 2026-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_historicaluser_bluesky_url_user_bluesky_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="enable_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
